### ISSUE TITLE
Work through amazon services?

### ISSUE THREAD

**Issue by DavidCo23** [DamianMehers/homebridge-alexa#1]
In your video into you mention trying to get it working through amazon services instead of the speaker. Did you have any luck with that?

**Comment by DamianMehers** [comment]
Hi David,

I didn't return to it, but I've since been working on bringing Alexa to the
Apple Watch <https://www.youtube.com/watch?v=HvXT5JIWwWw&feature=youtu.be>,
so I know how to do it, but am busy with other stuff!

Damian

http://about.me/dmehers
